# -*- coding: utf-8 -*-
"""text_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pUEDVI5laCJvpVBBmcUiVmVhl4dd11o
"""

!pip install "git+https://github.com/LostMa-ERC/Heurist-analyser.git"

from heurist.api.connection import HeuristAPIConnection
print("OK")

from lostma_db import LostmaDB
print("OK")

import pandas as pd
# create the client object
from lostma_db import LostmaDB

from dotenv import load_dotenv
import os 

load_dotenv()
login = os.getenv("HEURIST_LOGIN")
pwd = os.getenv("HEURIST_PASSWORD")
db = LostmaDB(login, pwd)

db.sync()

available_languages = ["dum (Middle Dutch)", "enm (Middle English)"]

texts = db.texts(available_languages)
texts

"""Maintenant qu'on a la table de base on reconstruit le reste avec les données liées des tables Genre, Story, Storyverse et Stemma."""

display(texts.columns)

"""Pas de méthode genre donc je dois aller chercher la table et merger manuellement"""

genre = db.table("Genre")

"""On vérifie la correspondance"""

[col for col in texts.columns if 'genre' in col.lower()]

texts = texts.merge(
    genre.rename(columns={"H-ID": "specific_genre H-ID"}),
    on="specific_genre H-ID",
    how="left",
    suffixes=("", "_genre")
)
texts

"""Pour story on ne conserve que les attributs qui nous intéressent :"""

story = db.table("Story")
story = story[["H-ID", "preferred_name", "is_part_of_storyverse H-ID"]]
story

"""Le merge sur la clé étrangère"""

texts = texts.merge(
    story.rename(columns={"preferred_name": "story_preferred_name"}),
    on="story_preferred_name",
    how="left",
)
texts

"""Même opération pour storyverse"""

storyverse = db.table("Storyverse")[["H-ID", "preferred_name"]]
storyverse["H-ID"] = storyverse["H-ID"].astype("Int64")

texts = texts.explode("story_is_part_of_storyverse H-ID")
texts["story_is_part_of_storyverse H-ID"] = texts["story_is_part_of_storyverse H-ID"].astype("Int64")

texts = texts.merge(
    storyverse.rename(columns={
        "H-ID": "story_is_part_of_storyverse H-ID",
        "preferred_name": "storyverse_preferred_name"
    }),
    on="story_is_part_of_storyverse H-ID",
    how="left"
)
texts

display(texts.columns)

"""
Même opération sur stemma (avec une conversion des types)"""

stemma = db.table("Stemma")
stemma

texts = texts.explode("in_stemma H-ID")
texts["in_stemma H-ID"] = texts["in_stemma H-ID"].astype("Int64")
stemma["H-ID"] = stemma["H-ID"].astype("Int64")

texts = texts.merge(
    stemma.rename(columns={"H-ID": "in_stemma H-ID"}),
    on="in_stemma H-ID",
    how="left"
)
texts

display(texts.columns)

"""Maintenant on nettoie la dataframe texts de tous les attributs non-nécessaires :"""

cols_to_drop = [
    "type_id_x",
    "language_COLUMN TRM-ID",
    "literary_form TRM-ID",
    "is_hypothetical TRM-ID",
    "claim_freetext",
    "peripheral",
    "verse_type TRM-ID",
    "rhyme_type TRM-ID",
    "Stanza_type TRM-ID",
    "tradition_status TRM-ID",
    "has_lost_older_version",
    "has_lost_older_version TRM-ID",
    "ancient_translations_freetext",
    "rewritings_freetext",
    "note_x",
    "date_of_creation_certainty TRM-ID",
    "is_adapted_by H-ID",
    "described_by_source H-ID",
    "described_at_URL",
    "reference_notes",
    "review_status",
    "review_status TRM-ID",
    "review_note",
    "H-ID_y",
    "type_id_y",
    "reference_stemma TRM-ID",
    "genre TRM-ID",
    "drawnStemma TRM-ID",
    "contam TRM-ID",
    "extraStemmContam TRM-ID",
    "rootType TRM-ID",
    "completeWits TRM-ID",
    "sourceText TRM-ID",
    "derivatives TRM-ID",
    "publicationType TRM-ID",

]

texts = texts.drop(columns=cols_to_drop)
texts