# -*- coding: utf-8 -*-
"""witness_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGg49BLyfFw7y4veGtKB_efEyVhmLH2g

Test d'un script pour la pipeline de transformation depuis les données hébergées sur Heurist jusqu'à un fichier TEI de sortie unique par texte et témoin.

Crédits : Virgile Reignier pour Heurist analyzer

Installations préalables :
"""

!pip install "git+https://github.com/LostMa-ERC/Heurist-analyser.git"

"""J'ai des conflits de dépendance avec Google colab donc je rajoute ces deux étapes pour vérifier que tout fonctionne :"""

from heurist.api.connection import HeuristAPIConnection
print("OK")

from lostma_db import LostmaDB
print("OK")

"""Pareil faudrait le rajouter à pip install mais je referai un truc propre plus tard"""

import pandas as pd

"""Ensuite on entre dans la DB avec ses login Heurist :"""

# create the client object
from lostma_db import LostmaDB

login = "maud.melinand"
pwd = "mojo"
db = LostmaDB(login, pwd)

"""On télécharge la base de données :"""

db.sync()

"""Vérification des tables disponibles : ça peut être utile de regarder le nom des tables"""

db.sql("SHOW TABLES")

"""On sélectionne les langages que l'on veut traiter : ici la sélection est constituée des corpus de Middle Dutch et Middle English, qui sont le lot pilote. La liste peut-être complétée au fur et à mesure de l'avancée du projet."""

available_languages = ["dum (Middle Dutch)", "enm (Middle English)"]

"""Ici on cherche à reconstruire seulement l'objet witness, qui comprend les tables : Witness, Part, DocumentTable, Digitization, Repository et PhysDesc.

"""

# création de l'objet witness avec les tables liées
witnesses_full = db.witnesses(available_languages, 0, 0)
# les deux arguments 0 me permettent de ne pas dropper les colonnes remplies à moins de 5% à l'inverde de la
# release de Virgile

"""J'ai récupéré le witnesses full de Virgile mais je veux virer les colonnes issues de TextTable, Genre et Story : (merci Claude)"""

cols_to_drop = [col for col in witnesses_full.columns
                if col.startswith("TextTable_")
                or col.startswith("Genre_")
                or col.startswith("Story_")]

"""On supprime et on récupère une table witness propre :"""

witnesses = witnesses_full.drop(columns=cols_to_drop)
witnesses

"""Maintenant on reconstruit en ajoutant les attributs liés de Part, DocumentTable et Digitization :

On récupère la table Parts de la DB (avec arguments) + on renomme l'attribut DocumentTable_H-ID en Wit_last_observed pour joindre les deux tables plus facilement :
"""

parts_data = db.parts(available_languages, 0, 0)
parts_data_renamed = parts_data.rename(columns={"DocumentTable_H-ID": "Witness_last_observed_in_doc H-ID"})

"""On fait une jointure (left join) entre les tables witness et parts :"""

witnesses = witnesses.merge(
    parts_data_renamed,
    on="Witness_last_observed_in_doc H-ID",
    how="left",
    suffixes=("_witness", "_part")
)
witnesses

"""Maintenant on recommence la même opération pour PhysDesc :"""

physdesc_data = db.table("PhysDesc")
physdesc_data_renamed = physdesc_data.rename(columns={"subject_of_description H-ID": "Witness_H-ID"})

witnesses = witnesses.merge(
    physdesc_data_renamed,
    on="Witness_H-ID",
    how="left",
    suffixes=("", "_physdesc")
)
witnesses

"""Attention, le PhysDesc n'existe à ma connaissance que pour les données scrappées dans Jonas (donc ça concerne le corpus français). Soit il faut trouver une solution pour les données dum et enm, soit on commente cette partie quand on le fait tourner. A REVOIR"""

display(witnesses)

"""Petite vérification pour voir ce qu'on a :"""

display(witnesses.columns)

"""On continue à nettoyer : les review sont inutiles."""

cols_to_drop = [
    "Witness_last_observed_in_doc Name",
    "Witness_is_unobserved",
    "Witness_claim_freetext",
    "Witness_scribe H-ID",
    "Witness_scribe Name",
    "Witness_number_of_hands",
    "Witness_scribe_note",
    "Witness_place_of_creation H-ID",
    "Witness_place_of_creation Name",
    "Witness_place_of_creation_source",
    "H-ID",
    "type_id",
    "has_decorations TRM-ID",
    "amount_of_illustrations TRM-ID",
    "above_top_line TRM-ID",
    "script_type TRM-ID",
    "subscript_type TRM-ID"
] + [
    col for col in witnesses_full.columns
    if col.startswith("TextTable_")
    or col.startswith("Genre_")
    or col.startswith("Story_")
    or col.startswith("review_")
]